### ISSUE TITLE
Error integrating Slack

### ISSUE THREAD

**Issue by alexanderpepper** [xavizalote/telescope-slack#8]
I'm seeing a success message that my Telescope instance is connected to Slack, but it's not working and the following error message is printed to the console:

```
Exception while invoking method 'requestSlackToken' { stack: 'TypeError: Cannot read property \'channel\' of undefined
at [object Object].Meteor.methods.requestSlackToken (lib/server/methods.js:15:39)
at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)
at maybeAuditArgumentChecks (livedata_server.js:1698:12)
at livedata_server.js:708:19
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at livedata_server.js:706:40
at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
at livedata_server.js:704:46
at tryCallTwo (/root/.meteor/packages/promise/.0.5.1.1550ocw++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
at doResolve (/root/.meteor/packages/promise/.0.5.1.1550ocw++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)',
```

**Comment by xavxyz** [comment]
Mmmh, seems like it didn't get the credentials from your Slack app. I'll give it a try this weekend!

**Comment by xavxyz** [comment]
I'm porting the package for Nova. If you still use the Telescope Legacy version, try to roll back to a previous working version of the package

**Comment by xavxyz** [comment]
Hey @alexanderpepper! Thanks for your support since the beginning of this package 📦 

The package is now ready for Nova, have you given a try to the new Telescope? It works better than ever 😉
